### ISSUE TITLE
spike: unique non linear 6 digit code generation

### ISSUE THREAD

**Issue by dviramontes** [mmmanyfold/pb#9]
The code can be generated from a hash based on their phone number
No more than 6-8 digits

**Comment by ZadenRB** [comment]
Should we use a more secure function (sha128, 256) and truncate, or find an algorithm that just produces short hashes?

**Comment by dviramontes** [comment]
@ZadenRB yep that's what I was thinking too. 
This is the library I was thinking of using: https://funcool.github.io/buddy-hashers/latest/

**Comment by ZadenRB** [comment]
@dviramontes I saw that one too. Not sure if it matters, but it does have out of date dependencies. Also, as far as I can tell doesn't actually have algorithms that support encryption via key. But if we use a slightly different method than the one above, that part isn't really a problem.
